apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hamburg-poi-map-app-dev
  annotations:
    argocd/app-name: hamburg-poi-map-app-dev
    backstage.io/kubernetes-id: hamburg-poi-map-app
    backstage.io/kubernetes-namespace: hamburg
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: devhub-test/hamburg-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.redhatdevhub.l07n.p1.openshiftapps.com/dev-pipelines/ns/hamburg/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.redhatdevhub.l07n.p1.openshiftapps.com/k8s/ns/hamburg/deployments/hamburg-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.redhatdevhub.l07n.p1.openshiftapps.com/#https://github.com/devhub-test/hamburg-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://hamburg-poi-map-app-hamburg.apps.redhatdevhub.l07n.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/hpgrahsl"
  system: workshop-system-hamburg
  consumesApis:
    - gateway-api-hamburg
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-hamburg
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/hpgrahsl"
